services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
